### ISSUE TITLE
Is it a memory issue?

### ISSUE THREAD

**Issue by balbir1313** [adaptive-cfd/WABBIT#52]
Code aborts by itself! I am using 64 GB memory on a small cluster

![Picture1](https://user-images.githubusercontent.com/83062448/172298951-1161b5f4-fd8a-4256-9d57-2d35b70d805b.png)

**Comment by balbir1313** [comment]
This is happening initially during adaptive grid refinement....jmax6 (coarser).

**Comment by tommy-engels** [comment]
Dear Balbir,
this is indeed a memory issue. The code allocates, on startup, a number of blocks that fits in your memory, which you pass with the --memory=64GB flag to WABBIT. It is not possible to know precisely in advance how much memory you will need, because the grid (and thus memory requirement) depends on the solution (which is unknown). 

In this simulation, more memory is required than you have available - hence the error. Try running the code with more memory (in your case, at least ~2 fold so 128GB). If you do not have that available, there are some tweaks we can do, but not by orders of magnitude. Such simulations simply require, to this day, large machines.

**Comment by balbir1313** [comment]
Dear Dr. Engels...…Thank you for the suggestions....Lemme try once more with more memory on another cluster. Thank you
